# Generated by Django 4.2.11 on 2024-11-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0060_studentmodulegoal"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseinstance",
            name="points_goal_enabled",
            field=models.BooleanField(
                default=False, verbose_name="LABEL_POINTS_GOAL_ENABLED"
            ),
        ),
    ]
