# Generated by Django 4.2.11 on 2024-11-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0061_courseinstance_points_goal_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseinstance",
            name="points_goal_enabled",
            field=models.BooleanField(
                default=True, verbose_name="LABEL_POINTS_GOAL_ENABLED"
            ),
        ),
    ]
